### ISSUE TITLE
Typerror: undefined is not a function

### ISSUE THREAD

**Issue by KevinHaeusler** [andreineculau/tastebin#13]
```
> tastebin@0.9.8 start /home/kevin/tastebin
> ./tastebin


/home/kevin/tastebin/index.coffee:34
      config.hljsStyles = execFileSync('/bin/sh', ['-c', "ls"], {
                          ^
TypeError: undefined is not a function
  at module.exports.exports (/home/kevin/tastebin/index.coffee:17:24)
  at Object.<anonymous> (/home/kevin/tastebin/tastebin.coffee:7:10)
  at Object.<anonymous> (/home/kevin/tastebin/tastebin.coffee:3:1)
  at Module._compile (module.js:456:26)
  at Object.loadFile (/home/kevin/tastebin/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/home/kevin/tastebin/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/home/kevin/tastebin/tastebin:4:1)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:902:3

npm ERR! weird error 8
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! not ok code 0
```

is the error message that I get when trying to run npm start

ive included ls in my path

```
PATH="$HOME/bin:$PATH"
```

ls /bin

```
bash                  dbus-uuidgen   kill        nc                ping6                    tar
bunzip2               dd             kmod        nc.openbsd        plymouth                 tempfile
busybox               df             less        netcat            plymouth-upstart-bridge  touch
bzcat                 dir            lessecho    netstat           ps                       true
bzcmp                 dmesg          lessfile    nisdomainname     pwd                      udevadm
bzdiff                dnsdomainname  lesskey     ntfs-3g           rbash                    ulockmgr_server
bzegrep               domainname     lesspipe    ntfs-3g.probe     readlink                 umount
bzexe                 dumpkeys       ln          ntfs-3g.secaudit  red                      uname
bzfgrep               echo           loadkeys    ntfs-3g.usermap   rm                       uncompress
bzgrep                ed             login       ntfscat           rmdir                    unicode_start
bzip2                 egrep          loginctl    ntfsck            rnano                    vdir
bzip2recover          false          lowntfs-3g  ntfscluster       running-in-container     which
bzless                fgconsole      ls          ntfscmp           run-parts                whiptail
bzmore                fgrep          lsblk       ntfsdump_logfile  sed                      ypdomainname
cat                   findmnt        lsmod       ntfsfix           setfont                  zcat
chgrp                 fuser          mkdir       ntfsinfo          setupcon                 zcmp
chmod                 fusermount     mknod       ntfsls            sh                       zdiff
chown                 git            mktemp      ntfsmftalloc      sh.distrib               zegrep
chvt                  grep           more        ntfsmove          sleep                    zfgrep
cp                    gunzip         mount       ntfstruncate      ss                       zforce
cpio                  gzexe          mountpoint  ntfswipe          static-sh                zgrep
dash                  gzip           mt          open              stty                     zless
date                  hostname       mt-gnu      openvt            su                       zmore
dbus-cleanup-sockets  ip             mv          pidof             sync                     znew
dbus-daemon           kbd_mode       nano        ping              tailf
```

**Comment by andreineculau** [comment]
which node version are you using?

``` bash
which node && node --version
```

`execFileSync` comes from https://github.com/andreineculau/tastebin/blob/master/index.coffee#L4 thus it looks safe to say that maybe you are running an earlier version of node 0.11.3

**Comment by KevinHaeusler** [comment]
updating npm worked thanks!

**Comment by andreineculau** [comment]
great! let me know if smth else looks off

On Thu, Dec 10, 2015 at 5:07 PM, chKaze notifications@github.com wrote:

> updating npm worked thanks!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/andreineculau/tastebin/issues/13#issuecomment-163671967
> .

## 

andreineculau.com http://www.andreineculau.com
